---
- name: Pull Ubuntu image & Create ghost container
  hosts: mymac
  # become: true
  # gather_facts: no
  
  tasks:
    - name: Kernel
      debug: msg="{{ ansible_kernel }}"

    - name: Hostname
      debug: msg="Target Host is  {{ ansible_hostname }}"

    - name: Pull nginx image
      community.general.docker_image:
        name: nginx
        source: pull
    
    - name: Create a nginx container1
      community.general.docker_container:
        name: nginx
        image: nginx
        detach: True
        state: started
        # volumes:
        #     - /etc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 8080:8080
        #command: ["sleep", "infinity"]