---
# tasks file for configure

- name: Display all variables/facts known for a host
  debug:
    msg: "System {{ inventory_hostname }}"

- name: Distribution
  debug:
    msg: "{{ ansible_distribution }}"

- name: Install the nginx package
  apt:
    pkg: nginx
    state: present
    update_cache: true
#   yum:
#     name: nginx
#     state: present
#     become: yes

- name: Create web root directory
  file:
    path: /var/www/html
    state: directory
    mode: 0755

- name: Copy index.html file
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
